#!/usr/bin/env bash
isWindows() {
    unameOut="$(uname -s)"
    case "${unameOut}" in
        Linux*)     machine=Linux;;
        Darwin*)    machine=Mac;;
        CYGWIN*)    machine=Cygwin;;
        MINGW*)     machine=MinGw;;
        *)          machine="UNKNOWN"
    esac
    if  [ "$machine" = "MinGw" ] || [ "$machine" = "Cygwin" ]; then
        true
        return
    fi
    false
}
convertPath() {
    if  isWindows; then
        printf "%s" $1 | sed 's|/c/|//c/|g'
        return
    fi
    printf "%s" $1
}

if isWindows; then
    WD=`convertPath $PWD`
    CILO_HOST_HOME=`convertPath $HOME`
    CILO_MOUNTS="-v $WD:/home/cilo/workspace -v $CILO_HOST_HOME/.cilo:/home/cilo/.cilo"
    winpty docker run -it --rm ${CILO_MOUNTS} --network="host" -e CILO_IS_NESTED="true" -e CILO_MOUNTS="${CILO_MOUNTS}" -e CILO_HOST_HOME="${CILO_HOST_HOME}" -e CILO_DOCKER_ADDRESS="host.docker.internal" -e CILO_HOST_OS="windows" cirrosoft/cilo:bootstrap $@
else
    CILO_MOUNTS="-v $PWD:/home/cilo/workspace -v $HOME/.cilo:/home/cilo/.cilo"
    docker run -it --rm ${CILO_MOUNTS} --network="host" -e CILO_IS_NESTED="true" -e CILO_MOUNTS="${CILO_MOUNTS}" -e CILO_DOCKER_ADDRESS="localhost" -e CILO_HOST_OS="linux" cirrosoft/cilo:bootstrap $@
fi


