#!/usr/bin/env sh
if [ -e "${CILO_PIPELINE}" ]; then
    # BASE IMPORT
    PIPELINE_FILE="/home/cilo/tmp/${CILO_PIPELINE}"
    touch "$PIPELINE_FILE"
    BASE_IMPORT=`cat <<EOF
import groovy.transform.BaseScript
@BaseScript CiloBaseScript base

EOF`
    # PREPROCESS PIPELINE
    echo "$BASE_IMPORT" >> "$PIPELINE_FILE"
    cat "${CILO_PIPELINE}" >> "$PIPELINE_FILE"
    cat "${PIPELINE_FILE}" | awk -f /home/cilo/bin/shell-substitution.awk > "${PIPELINE_FILE}.sub"
    rm "${PIPELINE_FILE}"
    mv "${PIPELINE_FILE}.sub" "${PIPELINE_FILE}"
    # PREPROCESS LIBRARIES
    for file in `find /home/cilo/workspace/${LIBRARY_PATH} -type f -name "*.cilo"`; do
        if ! [ -d "$file" ]; then
            if ! [ "$file" = '*' ]; then
                filename=`basename $file`
                tmpFile="/home/cilo/tmp/$filename"
                touch "$tmpFile"
                echo "$BASE_IMPORT" >> "$tmpFile"
                cat "${file}" >> "$tmpFile"
                cat "${tmpFile}" | awk -f /home/cilo/bin/shell-substitution.awk > "${tmpFile}.sub"
                rm "${tmpFile}"
                mv "${tmpFile}.sub" "${tmpFile}"
            fi
        fi
    done
    jarFiles=`find /home/cilo/workspace/${LIBRARY_PATH} -type f -name "*.jar" | tr '\n' ':'`
    groovy -cp ${jarFiles}/home/cilo/bin/:/home/cilo/tmp/:/home/cilo/workspace/${LIBRARY_PATH} "${PIPELINE_FILE}"
else
    echo "COULD NOT FIND PIPELINE FILE (${CILO_PIPELINE})."
fi
