#!/usr/bin/env sh
cat "/home/cilo/.cilo/tmp/secret/local/${1}.enc" | openssl enc -a -d -pass pass:`printf $SECRET_KEY` -aes-256-cbc > /home/cilo/secret/local/$1
if ! [ "$?" = "0" ]; then
    exit 1
fi
chmod 700 /home/cilo/secret/local/$1
exit 0
